import {ITEMS,RECIPES,fresh,init,act,weight,capacity,dist,serialize,restore,blocked} from './engine.js';
import {render,screenToTile,terrain} from './render.js';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s),key='ashlight-save-v1';let s,tab='bag',container=null,building=null,paused=false,lastEnd='',toastTimer,path=[];let corrupted=false;
try{const raw=localStorage.getItem(key);s=raw?restore(raw):null;corrupted=!!raw&&!s;}catch{}
s=s||init(fresh());const canvas=$('#world'),ctx=canvas.getContext('2d');
const zones={base:['寂靜營地','一小片安全，等待你親手重建。'],forest:['霧杉林地','風穿過枯枝，物資藏在樹影之下。'],ruins:['沉默街區','推開舊門，找回文明留下的零件。']};
function save(){try{localStorage.setItem(key,serialize(s));$('#saveStatus').textContent='進度已儲存';}catch{$('#saveStatus').textContent='無法儲存，請勿關閉分頁';}}
function toast(t){if(!t)return;$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function doAct(a){if(paused)return;const r=act(s,a,terrain);if(!r.ok){toast(r.msg);path=[];return false;}if(r.msg)toast(r.msg);save();update();return true;}
function cost(c){return Object.entries(c).map(([k,n])=>`${ITEMS[k].name} ${n}`).join(' · ');}
function inventory(b,click=false){let t=Object.entries(b).map(([k,n])=>`<${click?'button':'div'} class="item" ${click?`data-use="${k}"`:''} title="${ITEMS[k].name}"><span class="qty">${n}</span><span class="icon">${ITEMS[k].icon}</span><span>${ITEMS[k].name}</span></${click?'button':'div'}>`).join('');for(let i=Object.keys(b).length;i<8;i++)t+='<div class="item empty"></div>';return t;}
function update(){const z=zones[s.zone];$('#zoneName').textContent=z[0];$('#zoneDesc').textContent=z[1];$('#day').textContent='DAY '+String(s.day).padStart(2,'0');$('#phase').textContent=s.waveActive?'夜襲中 · 保持警戒':'探索時間 · 白晝';$('#vitals').innerHTML=[['生命','hp','✚'],['飽食','hunger','◒'],['水分','thirst','◈']].map(([n,k,i])=>`<div class="stat"><div><span>${i} ${n}</span><strong>${Math.ceil(s.player[k])} / 100</strong></div><div class="bar"><i style="width:${Math.max(0,s.player[k])}%"></i></div></div>`).join('');const beacon=s.buildings.some(b=>b.type==='beacon');$('#objectiveText').textContent=beacon?`信標已啟動。守住三波夜襲，等待救援。已完成 ${s.waveActive?s.wave-1:s.wave} / 3 波。`:'搜刮林地與舊公寓，取得 6 木材、6 金屬、3 電路板。回基地製作撤離信標。';$('#progress').style.width=(beacon?25+(s.waveActive?s.wave-1:s.wave)*25:8)+'%';$('#turnLabel').textContent=`回合 ${s.turn}`;$('#logs').innerHTML=s.logs.slice(0,4).map(t=>`<p>${esc(t)}</p>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
let html='';if(tab==='bag'){html=`<div class="panel-title"><h3>行囊</h3><span>${weight(s.inv).toFixed(1)} / ${capacity(s)} 負重</span></div><div class="items">${inventory(s.inv,true)}</div><p class="hint">點罐頭、淨水或繃帶使用。素材會自動堆疊。<br>裝備：${s.flags.spear?'強化長矛':'簡易長矛'} · 攻擊 ${(s.flags.spear?30:18)+(s.flags.power?6:0)}</p><div class="bag-actions">${s.zone==='base'?'<button id="stash">基地儲物箱</button>':''}<button id="nearby">附近容器</button></div>`;let c=container==='stash'?{id:'stash',name:'基地儲物箱',items:s.stash}:s.containers.find(c=>c.id===container&&dist(c,s.player)<=1);if(c){html+=`<div class="container-box"><div class="panel-title"><h3>${esc(c.name)}</h3><button id="closeContainer" aria-label="關閉容器">×</button></div>`;const keys=[...new Set([...Object.keys(c.items),...Object.keys(s.inv)])];html+=keys.map(k=>`<div class="transfer-row"><span>${ITEMS[k].icon} ${ITEMS[k].name} <small>箱 ${c.items[k]||0} / 包 ${s.inv[k]||0}</small></span><span><button data-take="${k}" ${!c.items[k]?'disabled':''}>取 1</button><button data-put="${k}" ${!s.inv[k]?'disabled':''}>存 1</button></span></div>`).join('');html+='</div>';}}
if(tab==='craft'){if(building)html+=`<div class="build-hint">放置${RECIPES[building].name}：點擊角色身旁兩格內的空地。材料只在成功放置後扣除。<br><button id="cancelBuild">取消放置</button></div>`;html+=Object.entries(RECIPES).map(([id,r])=>`<div class="recipe"><div><h4>${r.name}${r.flag&&s.flags[r.flag]?' ✓':''}</h4><p>${r.description}</p><p class="cost">${cost(r.cost)}</p></div><button data-craft="${id}" ${r.flag&&s.flags[r.flag]?'disabled':''}>${r.build?'建造':'製作'}</button></div>`).join('');html+='<p class="hint">建物只能放在基地空地。路障擋住自己與敵人；請保留出入通道。</p>';}
if(tab==='map'){html=`<div class="panel-title"><h3>遠征地點</h3><span>切換地區消耗一回合</span></div>`;for(const [id,[name]]of Object.entries(zones))html+=`<button class="travel ${s.zone===id?'current':''}" data-travel="${id}" ${s.zone===id||s.waveActive?'disabled':''}><strong>${id==='base'?'⌂':id==='forest'?'♧':'▥'} ${name}</strong><span>${id==='base'?'儲物 · 建造 · 三波守夜':id==='forest'?'木材與食水 · 少量威脅':'電路板與金屬 · 中度威脅'}</span></button>`;html+=`<button id="night" class="night" ${!beacon||s.zone!=='base'||s.waveActive?'disabled':''}>☾ ${s.waveActive?'守夜進行中':`開始第 ${s.wave+1} 波守夜`}</button><p class="hint">守夜前先補滿生命、食物和水。建議先製作強化長矛與營火。</p>`;}
$('#panel').innerHTML=html;bindPanel();if(s.perk&&!paused)showPerks();if(s.status!=='playing'&&lastEnd!==s.status){lastEnd=s.status;ending();}}
function bindPanel(){document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{if(['food','water','med'].includes(b.dataset.use))doAct({type:'use',item:b.dataset.use});else toast('這是製作素材，可前往製作面板使用');});$('#stash')?.addEventListener('click',()=>{container=container==='stash'?null:'stash';update();});$('#nearby')?.addEventListener('click',interact);$('#closeContainer')?.addEventListener('click',()=>{container=null;update();});document.querySelectorAll('[data-take]').forEach(b=>b.onclick=()=>doAct({type:'transfer',id:container,item:b.dataset.take,n:1}));document.querySelectorAll('[data-put]').forEach(b=>b.onclick=()=>doAct({type:'transfer',id:container,item:b.dataset.put,n:1,dir:'put'}));document.querySelectorAll('[data-craft]').forEach(b=>b.onclick=()=>{let id=b.dataset.craft;if(RECIPES[id].build){if(s.zone!=='base'){toast('請先返回基地建造');return;}building=id;path=[];update();toast('點選身旁兩格內的空地放置');}else doAct({type:'craft',recipe:id});});$('#cancelBuild')?.addEventListener('click',()=>{building=null;update();});document.querySelectorAll('[data-travel]').forEach(b=>b.onclick=()=>{container=null;building=null;path=[];doAct({type:'travel',zone:b.dataset.travel});});$('#night')?.addEventListener('click',()=>doAct({type:'night'}));}
function interact(){if(paused)return;const c=s.containers.filter(c=>dist(c,s.player)<=1).sort((a,b)=>Object.keys(b.items).length-Object.keys(a.items).length)[0];if(c){container=c.id;tab='bag';update();toast('已打開'+c.name);}else toast('請靠近箱子或衣櫃至相鄰格，再搜刮');}
function modal(html){path=[];paused=true;$('#modalCard').innerHTML=html;$('#modal').classList.remove('hidden');$('#modalCard').querySelector('button')?.focus();}
function close(){paused=false;$('#modal').classList.add('hidden');canvas.focus();update();}
function tutorial(){modal(`<span class="big-symbol">◈</span><p class="eyebrow">A SMALL LIGHT. A NEW BEGINNING.</p><h2 id="modalTitle">活下去，直到天亮。</h2><p>文明熄滅後，你在荒原建立最後的營地。帶回零件，讓撤離信標再次發光。</p><ol><li>WASD／方向按鈕移動，或點選地面自動尋路。</li><li>站到容器旁按 E 搜刮，物資可逐件存取。</li><li>到林地找木材，到舊公寓找電路板。</li><li>製作強化長矛，回基地建造信標。</li><li>遠征面板開始守夜。守住三波即獲勝。</li></ol><p>敵人相鄰時按空白鍵攻擊。移動、攻擊與觀察才會推進時間；面板操作不耗回合。每步自動存檔。</p>${corrupted?'<p class="warning">存檔資料損壞，已安全建立新遊戲。</p>':''}<button id="begin" class="accent">${s.turn?'返回遠征':'開始遠征 →'}</button>`);$('#begin').onclick=close;}
function showPerks(){modal(`<p class="eyebrow">ADAPT & SURVIVE</p><h2 id="modalTitle">你變得更強了</h2><p>選一項生存專長。搜空容器或擊倒威脅可累積經驗。</p><button class="perk" data-perk="power">獵手直覺 <small>攻擊力 +6（不重複累加）</small></button><button class="perk" data-perk="guard">堅韌意志 <small>每次承受傷害由 6 降至 4</small></button><button class="perk" data-perk="care">緊急處置 <small>立即回復 40 生命</small></button>`);document.querySelectorAll('[data-perk]').forEach(b=>b.onclick=()=>{paused=false;$('#modal').classList.add('hidden');doAct({type:'perk',perk:b.dataset.perk});});}
function pauseMenu(){if(s.status!=='playing'){ending();return;}modal(`<p class="eyebrow">TAKE A BREATH</p><h2 id="modalTitle">遠征已暫停</h2><p>進度已儲存在這個瀏覽器。你可以放心休息。</p><button id="resume" class="accent">繼續遠征</button><button id="instructions">操作說明</button><button id="restart">重新開始</button>`);$('#resume').onclick=close;$('#instructions').onclick=tutorial;$('#restart').onclick=confirmRestart;}
function confirmRestart(){modal('<h2 id="modalTitle">重啟這趟遠征？</h2><p>目前存檔將被新遊戲取代，無法還原。</p><button id="cancelRestart" class="accent">保留進度</button><button id="confirmRestart">確認重新開始</button>');$('#cancelRestart').onclick=close;$('#confirmRestart').onclick=newGame;}
function newGame(){s=init(fresh());tab='bag';container=null;building=null;lastEnd='';save();update();tutorial();}
function ending(){modal(`<span class="big-symbol">${s.status==='won'?'✦':'◌'}</span><p class="eyebrow">${s.status==='won'?'SIGNAL RECEIVED':'SIGNAL LOST'}</p><h2 id="modalTitle">${s.status==='won'?'曙光，終於抵達。':'餘燼仍在等待。'}</h2><p>${s.status==='won'?'你守住了三次長夜。救援艇循著信標而來，這趟旅程終於有了歸途。':'你的生命已耗盡。下次記得帶足水、製作繃帶，並在敵人靠近時主動攻擊。'}</p><p>生存 ${s.day} 天 · ${s.turn} 回合 · 排除 ${s.kills} 個威脅</p><button id="again" class="accent">再一次遠征 →</button>`);$('#again').onclick=newGame;}
function move(dx,dy){container=null;doAct({type:'move',dx,dy});}
for(const b of document.querySelectorAll('[data-move]'))b.onclick=()=>{path=[];const[dx,dy]=b.dataset.move.split(',').map(Number);move(dx,dy);};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;update();});$('#attack').onclick=()=>{path=[];doAct({type:'attack'});};$('#interact').onclick=interact;$('#wait').onclick=()=>doAct({type:'wait'});$('#help').onclick=tutorial;$('#pause').onclick=pauseMenu;
window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.repeat)return;if(e.code==='Escape'){if(paused&&!s.perk&&s.status==='playing')close();else if(!paused)pauseMenu();return;}if(paused)return;const keymap={KeyW:[0,-1],ArrowUp:[0,-1],KeyD:[1,0],ArrowRight:[1,0],KeyS:[0,1],ArrowDown:[0,1],KeyA:[-1,0],ArrowLeft:[-1,0]};if(keymap[e.code]){e.preventDefault();path=[];move(...keymap[e.code]);}if(e.code==='Space'){e.preventDefault();path=[];doAct({type:'attack'});}if(e.code==='KeyE')interact();if(e.code==='KeyR')doAct({type:'wait'});});
function route(tx,ty){const queue=[[s.player.x,s.player.y,[]]],seen=new Set;while(queue.length){const[x,y,p]=queue.shift();if(x===tx&&y===ty)return p;for(const[dx,dy]of [[0,-1],[1,0],[0,1],[-1,0]]){let nx=x+dx,ny=y+dy,k=nx+','+ny;if(!seen.has(k)&&!blocked(s,nx,ny,terrain)&&!s.enemies.some(e=>e.x===nx&&e.y===ny)){seen.add(k);queue.push([nx,ny,[...p,[dx,dy]]]);}}}return null;}
canvas.addEventListener('pointerdown',e=>{if(paused)return;const r=canvas.getBoundingClientRect(),p=screenToTile(e.clientX-r.left,e.clientY-r.top,r.width,r.height);if(!p)return;let x=Math.round(p.x),y=Math.round(p.y);if(building){const ok=doAct({type:'craft',recipe:building,x,y});if(ok){building=null;update();}return;}const enemy=s.enemies.find(v=>v.x===x&&v.y===y);if(enemy&&dist(enemy,s.player)<=1){doAct({type:'attack'});return;}const c=s.containers.find(v=>v.x===x&&v.y===y);if(c&&dist(c,s.player)<=1){container=c.id;tab='bag';update();return;}if(c){const options=[[x-1,y],[x+1,y],[x,y-1],[x,y+1]].map(([a,b])=>route(a,b)).filter(Boolean).sort((a,b)=>a.length-b.length);path=options[0]||[];if(!path.length)toast('無法抵達容器');else toast('接近容器後按 E 搜刮');return;}const found=route(x,y);if(found)path=found;else toast('此處無法抵達');});
let lastStep=0;function frame(t){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}ctx.setTransform(d,0,0,d,0,0);render(ctx,s,r.width,r.height,{building});if(path.length&&!paused&&t-lastStep>180){if(s.enemies.some(e=>dist(e,s.player)<=2)){path=[];toast('敵人接近，自動移動已停止');}else{const[dx,dy]=path.shift();move(dx,dy);lastStep=t;}}requestAnimationFrame(frame);}update();requestAnimationFrame(frame);if(!s.turn&&s.status==='playing')tutorial();else if(corrupted)tutorial();document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused&&s.status==='playing')pauseMenu();});
