export const ITEMS={wood:{name:'木材',icon:'🪵',w:.5},metal:{name:'廢金屬',icon:'⚙',w:.5},cloth:{name:'布料',icon:'▧',w:.5},circuit:{name:'電路板',icon:'▣',w:1},food:{name:'罐頭',icon:'🥫',w:1},water:{name:'淨水',icon:'💧',w:1},med:{name:'繃帶',icon:'✚',w:1}};
export const RECIPES={bandage:{name:'急救繃帶',cost:{cloth:2},item:'med',description:'立即可用，回復 35 生命'},spear:{name:'強化長矛',cost:{wood:3,metal:2},flag:'spear',description:'攻擊由 18 提升至 30'},pack:{name:'擴充背包',cost:{cloth:3,metal:2},flag:'pack',description:'容量由 20 提升至 32'},beacon:{name:'撤離信標',cost:{wood:6,metal:6,circuit:3},build:'beacon',description:'建造後守住三次夜襲，即可撤離'},barricade:{name:'防禦路障',cost:{wood:3},build:'barricade',description:'阻擋移動，吸收 3 次敵人攻擊'},fire:{name:'營火',cost:{wood:2,metal:1},build:'fire',description:'每次守夜前回復 20 生命'}};
export function fresh(){return{version:1,zone:'base',player:{x:8,y:10,hp:100,hunger:100,thirst:100},inv:{wood:2,metal:1,cloth:2,food:3,water:3},stash:{},flags:{},buildings:[],containers:[],enemies:[],zones:{},day:1,time:0,kills:0,xp:0,level:0,perk:null,wave:0,waveActive:false,status:'playing',logs:['在荒野中醒來。搜集材料，點亮撤離信標。'],seed:73571,turn:0,visited:0,selected:null};}
export const weight=bag=>Object.entries(bag).reduce((n,[k,v])=>n+(ITEMS[k]?.w||0)*v,0);
export const capacity=s=>s.flags.pack?32:20;
export const dist=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
function add(b,k,n){b[k]=(b[k]||0)+n;if(b[k]<=0)delete b[k];}
function log(s,t){s.logs.unshift(t);s.logs=s.logs.slice(0,8);}
export function random(s){s.seed=(s.seed*1664525+1013904223)>>>0;return s.seed/4294967296;}
export function objects(zone){if(zone==='base')return[{id:'supply',x:7,y:8,name:'救援補給箱',items:{wood:4,metal:4,cloth:4,food:2,water:2}}];if(zone==='forest')return[{id:'timber1',x:5,y:7,name:'倒木堆',items:{wood:8,cloth:2}},{id:'timber2',x:12,y:11,name:'林間補給',items:{wood:8,food:3,water:3}}];return[{id:'locker',x:6,y:6,name:'舊公寓衣櫃',items:{cloth:5,food:2,water:2}},{id:'cabinet',x:11,y:6,name:'維修櫃',items:{metal:8,circuit:2}},{id:'crate',x:12,y:12,name:'封存工具箱',items:{metal:6,circuit:2,med:2}}];}
export function init(s){s.containers=objects('base');return s;}
export function blocked(s,x,y,terrain){return x<1||y<1||x>16||y>16||['wall','tree'].includes(terrain(s.zone,x,y))||s.buildings.some(b=>b.zone===s.zone&&b.x===x&&b.y===y)||s.containers.some(c=>c.x===x&&c.y===y);}
function freeTile(s,x,y,terrain,avoidPlayer=false){const cells=[];for(let a=1;a<=16;a++)for(let b=1;b<=16;b++)if(!blocked(s,a,b,terrain)&&!s.enemies.some(e=>e.x===a&&e.y===b)&&(!avoidPlayer||s.player.x!==a||s.player.y!==b))cells.push({x:a,y:b});return cells.sort((a,b)=>dist(a,{x,y})-dist(b,{x,y}))[0]||null;}
function award(s,n){s.xp+=n;if(s.xp>=(s.level+1)*3&&!s.perk){s.perk=true;log(s,'成長機會：選擇一項生存專長。');}}
function endCheck(s){if(s.player.hp<=0){s.player.hp=0;s.status='lost';log(s,'訊號沉寂。這趟旅程結束了。');}}
export function tick(s,terrain){if(s.status!=='playing')return;s.turn++;s.time++;s.player.hunger=Math.max(0,s.player.hunger-.3);s.player.thirst=Math.max(0,s.player.thirst-.4);if(!s.player.hunger||!s.player.thirst)s.player.hp-=3;
for(const e of s.enemies){if(e.hp<=0)continue;if(dist(e,s.player)<=1){s.player.hp-=s.flags.guard?4:6;continue;}const opts=[[Math.sign(s.player.x-e.x),0],[0,Math.sign(s.player.y-e.y)]].filter(([a,b])=>a||b);for(const [dx,dy] of opts){const x=e.x+dx,y=e.y+dy;const b=s.buildings.find(b=>b.zone===s.zone&&b.x===x&&b.y===y);if(b){if(b.type==='barricade'){b.hp--;if(b.hp<=0){s.buildings=s.buildings.filter(v=>v!==b);log(s,'路障被摧毀。');}}break;}if(!blocked(s,x,y,terrain)&&!s.enemies.some(v=>v!==e&&v.hp>0&&v.x===x&&v.y===y)&&!(s.player.x===x&&s.player.y===y)){e.x=x;e.y=y;break;}}}
if(s.waveActive&&!s.enemies.length){s.waveActive=false;s.day++;s.player.hp=Math.min(100,s.player.hp+10);log(s,`第 ${s.wave} 波已守住。恢復 10 生命。`);if(s.wave>=3){s.status='won';log(s,'救援艇收到訊號。你成功撤離！');}}
endCheck(s);}
export function act(s,a,terrain){if(s.status!=='playing')return{ok:false,msg:'此局已結束'};let msg='';const fail=t=>({ok:false,msg:t});if(s.perk&&a.type!=='perk')return fail('請先選擇生存專長');
if(a.type==='move'){const x=s.player.x+a.dx,y=s.player.y+a.dy;if(!Number.isInteger(a.dx)||!Number.isInteger(a.dy)||Math.abs(a.dx)+Math.abs(a.dy)!==1||blocked(s,x,y,terrain)||s.enemies.some(e=>e.x===x&&e.y===y))return fail('前方無法通行');s.player.x=x;s.player.y=y;tick(s,terrain);}
else if(a.type==='attack'){const e=s.enemies.filter(e=>dist(e,s.player)<=1).sort((a,b)=>a.hp-b.hp)[0];if(!e)return fail('靠近敵人至相鄰格再攻擊');e.hp-=(s.flags.spear?30:18)+(s.flags.power?6:0);msg='長矛命中';if(e.hp<=0){s.enemies=s.enemies.filter(v=>v!==e);s.kills++;award(s,1);const drop={cloth:1};s.containers.push({id:'drop'+s.turn+'-'+e.id,x:e.x,y:e.y,name:'拾荒者遺留物',items:drop});msg='威脅排除，留下布料';}tick(s,terrain);}
else if(a.type==='transfer'){if(a.n!==undefined&&(!Number.isInteger(a.n)||a.n<=0))return fail('轉移數量必須為正整數');if(a.dir!==undefined&&a.dir!=='put')return fail('未知轉移方向');let other;if(a.id==='stash'){if(s.zone!=='base')return fail('儲物箱只在基地可用');other=s.stash;}else{const c=s.containers.find(c=>c.id===a.id);if(!c||dist(c,s.player)>1)return fail('請先移至容器旁');other=c.items;}const from=a.dir==='put'?s.inv:other,to=a.dir==='put'?other:s.inv;const n=Math.min(a.n||1,from[a.item]||0);if(!Object.hasOwn(ITEMS,a.item)||!n)return fail('沒有可轉移物品');if(to===s.inv&&weight(to)+ITEMS[a.item].w*n>capacity(s))return fail('背包已滿，存回基地或先使用補給');add(from,a.item,-n);add(to,a.item,n);msg=`已${a.dir==='put'?'存放':'取得'} ${ITEMS[a.item].name} ×${n}`;if(a.id!=='stash'&&!a.dir&&Object.values(other).every(n=>!n)){const c=s.containers.find(c=>c.id===a.id);if(!c.claimed){c.claimed=true;award(s,1);}}}
else if(a.type==='use'){const k=a.item;if(!['food','water','med'].includes(k)||!s.inv[k])return fail('沒有這項補給');const stat=k==='food'?'hunger':k==='water'?'thirst':'hp';if(s.player[stat]>=100)return fail('目前不需要補充');add(s.inv,k,-1);s.player[stat]=Math.min(100,s.player[stat]+(k==='med'?35:45));msg=`使用${ITEMS[k].name}`;}
else if(a.type==='craft'){const r=Object.hasOwn(RECIPES,a.recipe)?RECIPES[a.recipe]:null;if(!r)return fail('未知配方');if(r.flag&&s.flags[r.flag])return fail('已完成這項升級');if(r.build&&s.zone!=='base')return fail('只能在基地建造');if(r.build==='beacon'&&s.buildings.some(b=>b.type==='beacon'))return fail('已建造信標');if(Object.entries(r.cost).some(([k,n])=>(s.inv[k]||0)<n))return fail('背包材料不足');if(r.item&&weight(s.inv)-weight(r.cost)+ITEMS[r.item].w>capacity(s))return fail('背包已滿');if(r.build){if(!Number.isInteger(a.x)||!Number.isInteger(a.y)||dist(s.player,a)>2||blocked(s,a.x,a.y,terrain)||(a.x===s.player.x&&a.y===s.player.y)||s.enemies.some(e=>e.x===a.x&&e.y===a.y))return fail('選擇身旁兩格內的空地，不能重疊角色或物件');}for(const[k,n]of Object.entries(r.cost))add(s.inv,k,-n);if(r.item)add(s.inv,r.item,1);if(r.flag)s.flags[r.flag]=true;if(r.build)s.buildings.push({type:r.build,x:a.x,y:a.y,zone:'base',hp:3});msg=`完成：${r.name}`;}
else if(a.type==='travel'){if(s.waveActive)return fail('守夜期間無法離開基地');if(!['base','forest','ruins'].includes(a.zone)||a.zone===s.zone)return fail('已在此區域');s.zones[s.zone]={containers:s.containers,enemies:s.enemies};s.zone=a.zone;s.containers=s.zones[a.zone]?.containers||objects(a.zone);s.enemies=s.zones[a.zone]?.enemies|| (a.zone==='ruins'?[{id:'r1',x:10,y:10,hp:28},{id:'r2',x:13,y:7,hp:28}]:a.zone==='forest'?[{id:'f1',x:13,y:12,hp:28}]:[]);const arrival=freeTile(s,8,10,terrain);if(!arrival){s.status='lost';log(s,'所有落腳點已封閉，遠征結束。');return{ok:true,msg:'沒有可用落腳點'};}s.player.x=arrival.x;s.player.y=arrival.y;s.visited++;if(!s.zones[a.zone]&&a.zone!=='base'){if(random(s)>.5){s.player.thirst=Math.max(0,s.player.thirst-8);msg='探索事件：乾燥熱風，口渴 -8';}else{add(s.stash,'food',1);msg='探索事件：發現藏糧，已標記送回基地儲物箱';}}tick(s,terrain);}
else if(a.type==='night'){if(s.zone!=='base'||s.waveActive||!s.buildings.some(b=>b.type==='beacon'))return fail('先在基地建造信標，再開始守夜');s.wave++;s.waveActive=true;if(s.buildings.some(b=>b.type==='fire'))s.player.hp=Math.min(100,s.player.hp+20);const points=[[4,10],[12,10],[8,14],[8,4]];s.enemies=[];for(const [i,[x,y]]of points.slice(0,s.wave+1).entries()){const p=freeTile(s,x,y,terrain,true);if(p)s.enemies.push({id:`w${s.wave}-${i}`,x:p.x,y:p.y,hp:28});}msg=`第 ${s.wave} 波夜襲開始！`;}else if(a.type==='wait'){tick(s,terrain);msg='觀察四周…';}
else if(a.type==='perk'){if(!s.perk||!['power','guard','care'].includes(a.perk))return fail('目前沒有可選專長');if(a.perk==='care')s.player.hp=Math.min(100,s.player.hp+40);else s.flags[a.perk]=true;s.level++;s.perk=null;msg='生存專長已獲得';}else return fail('未知動作');if(msg)log(s,msg);return{ok:true,msg};}
export function serialize(s){return JSON.stringify(s);}
export function restore(raw){try{
const s=JSON.parse(raw),obj=v=>!!v&&typeof v==='object'&&!Array.isArray(v),int=(v,min=0,max=100000)=>Number.isInteger(v)&&v>=min&&v<=max,point=v=>obj(v)&&int(v.x,1,16)&&int(v.y,1,16),bag=v=>obj(v)&&Object.entries(v).every(([k,n])=>Object.hasOwn(ITEMS,k)&&int(n,1,999)),containers=v=>Array.isArray(v)&&v.length<=200&&v.every(c=>point(c)&&typeof c.id==='string'&&c.id.length<120&&typeof c.name==='string'&&c.name.length<120&&bag(c.items)&&(c.claimed===undefined||typeof c.claimed==='boolean')),enemies=v=>Array.isArray(v)&&v.length<=30&&v.every(e=>point(e)&&typeof e.id==='string'&&int(e.hp,1,100)),zone=v=>['base','forest','ruins'].includes(v);
if(!obj(s)||s.version!==1||!zone(s.zone)||!['playing','won','lost'].includes(s.status)||!point(s.player)||!bag(s.inv)||!bag(s.stash)||!obj(s.flags)||!obj(s.zones)||!containers(s.containers)||!enemies(s.enemies)||!Array.isArray(s.buildings)||!Array.isArray(s.logs)||s.logs.some(t=>typeof t!=='string'||t.length>300)||s.logs.length>8)throw 0;
for(const k of ['hp','hunger','thirst'])if(!Number.isFinite(s.player[k])||s.player[k]<0||s.player[k]>100)throw 0;
for(const k of ['turn','time','kills','xp','level','visited'])if(!int(s[k]))throw 0;
if(!int(s.day,1)||!int(s.wave,0,3)||!int(s.seed,0,4294967295)||typeof s.waveActive!=='boolean'||![null,true].includes(s.perk)||Object.entries(s.flags).some(([k,v])=>!['spear','pack','power','guard'].includes(k)||typeof v!=='boolean'))throw 0;
if(s.buildings.length>256||s.buildings.some(b=>!point(b)||!['fire','beacon','barricade'].includes(b.type)||b.zone!=='base'||!int(b.hp,1,3)))throw 0;
for(const [k,v]of Object.entries(s.zones))if(!zone(k)||!obj(v)||!containers(v.containers)||!enemies(v.enemies))throw 0;
return s;}catch{return null;}}
